swagger: '2.0'
info:
  description: '"Spring Boot REST API for manage holidays"'
  version: 1.0.0
  title: Api Holiday Application Documentation
  license:
    name: Apache License Version 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0"'
host: 'localhost:9090'
basePath: /
tags:
  - name: holiday-controller
    description: Holiday Controller
paths:
  /holiday:
    get:
      tags:
        - holiday-controller
      summary: getHolidays
      operationId: getHolidaysUsingGET
      produces:
        - application/xml
        - application/fixedposition
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/HolidaysDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - holiday-controller
      summary: saveHolidays
      operationId: saveHolidaysUsingPOST
      consumes:
        - application/xml
        - application/fixedposition
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: holidaysDTO
          description: holidaysDTO
          required: true
          schema:
            $ref: '#/definitions/HolidaysDTO'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/HolidaysDTO'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/holiday/{id}':
    get:
      tags:
        - holiday-controller
      summary: getHoliday
      operationId: getHolidayUsingGET
      produces:
        - application/xml
        - application/fixedposition
        - application/json
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/HolidaysDTO'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  HolidayDTO:
    type: object
    properties:
      city:
        type: string
      country:
        type: string
      date:
        type: string
        example: dd-MM-yyyy
      description:
        type: string
      state:
        type: string
    title: HolidayDTO
  HolidaysDTO:
    type: object
    properties:
      holidays:
        type: array
        items:
          $ref: '#/definitions/HolidayDTO'
      year:
        type: integer
        format: int32
    title: HolidaysDTO
