swagger: '2.0'
info:
  description: '"Spring Boot REST API for manage holidays"'
  version: 1.0.0
  title: Api Holiday Application Documentation
  license:
    name: Apache License Version 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0"'
host: 'localhost:9090'
basePath: /
tags:
  - name: applied-holiday-controller
    description: Applied Holiday Controller
  - name: holiday-controller
    description: Holiday Controller
paths:
  /appliedHoliday:
    get:
      tags:
        - applied-holiday-controller
      summary: listHolidays
      operationId: listHolidaysUsingGET
      produces:
        - application/xml
        - application/fixedposition
        - application/json
      parameters:
        - name: page
          in: query
          description: page
          required: false
          type: integer
          default: 0
          format: int32
        - name: size
          in: query
          description: size
          required: false
          type: integer
          default: 20
          format: int32
        - name: year
          in: query
          description: year
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AppliedHolidayResultList'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /holiday:
    get:
      tags:
        - holiday-controller
      summary: listMonthDayHolidays
      operationId: listMonthDayHolidaysUsingGET
      produces:
        - application/xml
        - application/fixedposition
        - application/json
      parameters:
        - name: page
          in: query
          description: page
          required: false
          type: integer
          default: 0
          format: int32
        - name: size
          in: query
          description: size
          required: false
          type: integer
          default: 20
          format: int32
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MonthDayHolidayResultList'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - holiday-controller
      summary: saveHoliday
      operationId: saveHolidayUsingPOST
      consumes:
        - application/xml
        - application/fixedposition
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: monthDayHoliday
          description: monthDayHoliday
          required: true
          schema:
            $ref: '#/definitions/MonthDayHoliday'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MonthDayHoliday'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - holiday-controller
      summary: updateHoliday
      operationId: updateHolidayUsingPUT
      consumes:
        - application/xml
        - application/fixedposition
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: monthDayHoliday
          description: monthDayHoliday
          required: true
          schema:
            $ref: '#/definitions/MonthDayHoliday'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MonthDayHoliday'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/holiday/{id}':
    get:
      tags:
        - holiday-controller
      summary: getHoliday
      operationId: getHolidayUsingGET
      produces:
        - application/xml
        - application/fixedposition
        - application/json
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MonthDayHoliday'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  AppliedHoliday:
    type: object
    properties:
      city:
        type: string
      country:
        type: string
      date:
        type: string
        format: date
      description:
        type: string
      state:
        type: string
    title: AppliedHoliday
  AppliedHolidayResultList:
    type: object
    properties:
      holidays:
        type: array
        items:
          $ref: '#/definitions/AppliedHoliday'
      total:
        type: integer
        format: int64
      year:
        type: integer
        format: int32
    title: AppliedHolidayResultList
  MonthDayHoliday:
    type: object
    properties:
      city:
        type: string
      country:
        type: string
      dayOfMonth:
        type: integer
        format: int32
      description:
        type: string
      id:
        type: integer
        format: int64
      month:
        type: integer
        format: int32
      state:
        type: string
    title: MonthDayHoliday
  MonthDayHolidayResultList:
    type: object
    properties:
      holidays:
        type: array
        items:
          $ref: '#/definitions/MonthDayHoliday'
      total:
        type: integer
        format: int64
    title: MonthDayHolidayResultList
