/**
 * Api Holiday Application Documentation
 * \"Spring Boot REST API for manage holidays\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { MonthDayHoliday } from '../model/monthDayHoliday';
import { MonthDayHolidayResultList } from '../model/monthDayHolidayResultList';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class HolidayControllerService {

    protected basePath = 'http://localhost:9090';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getHoliday
     * 
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getHolidayUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<MonthDayHoliday>;
    public getHolidayUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MonthDayHoliday>>;
    public getHolidayUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MonthDayHoliday>>;
    public getHolidayUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getHolidayUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/fixedposition',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<MonthDayHoliday>(`${this.basePath}/holiday/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * listMonthDayHolidays
     * 
     * @param page page
     * @param size size
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listMonthDayHolidaysUsingGET(page?: number, size?: number, observe?: 'body', reportProgress?: boolean): Observable<MonthDayHolidayResultList>;
    public listMonthDayHolidaysUsingGET(page?: number, size?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MonthDayHolidayResultList>>;
    public listMonthDayHolidaysUsingGET(page?: number, size?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MonthDayHolidayResultList>>;
    public listMonthDayHolidaysUsingGET(page?: number, size?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('page', <any>page);
        }
        if (size !== undefined && size !== null) {
            queryParameters = queryParameters.set('size', <any>size);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/xml',
            'application/fixedposition',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<MonthDayHolidayResultList>(`${this.basePath}/holiday`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * saveHoliday
     * 
     * @param monthDayHoliday monthDayHoliday
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveHolidayUsingPOST(monthDayHoliday: MonthDayHoliday, observe?: 'body', reportProgress?: boolean): Observable<MonthDayHoliday>;
    public saveHolidayUsingPOST(monthDayHoliday: MonthDayHoliday, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MonthDayHoliday>>;
    public saveHolidayUsingPOST(monthDayHoliday: MonthDayHoliday, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MonthDayHoliday>>;
    public saveHolidayUsingPOST(monthDayHoliday: MonthDayHoliday, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (monthDayHoliday === null || monthDayHoliday === undefined) {
            throw new Error('Required parameter monthDayHoliday was null or undefined when calling saveHolidayUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/xml',
            'application/fixedposition',
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<MonthDayHoliday>(`${this.basePath}/holiday`,
            monthDayHoliday,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateHoliday
     * 
     * @param monthDayHoliday monthDayHoliday
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateHolidayUsingPUT(monthDayHoliday: MonthDayHoliday, observe?: 'body', reportProgress?: boolean): Observable<MonthDayHoliday>;
    public updateHolidayUsingPUT(monthDayHoliday: MonthDayHoliday, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MonthDayHoliday>>;
    public updateHolidayUsingPUT(monthDayHoliday: MonthDayHoliday, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MonthDayHoliday>>;
    public updateHolidayUsingPUT(monthDayHoliday: MonthDayHoliday, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (monthDayHoliday === null || monthDayHoliday === undefined) {
            throw new Error('Required parameter monthDayHoliday was null or undefined when calling updateHolidayUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/xml',
            'application/fixedposition',
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<MonthDayHoliday>(`${this.basePath}/holiday`,
            monthDayHoliday,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
