/**
 * Api Holiday Application Documentation
 * \"Spring Boot REST API for manage holidays\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Account { 
    agencia?: number;
    ativo?: boolean;
    id?: number;
    limite?: number;
    numero?: number;
    saldo?: number;
    senha?: string;
    titular?: number;
}
